[package]
name = "stroop-cli"
description = "Command-line interface for Stroop VM"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "stroop"
path = "src/main.rs"

[dependencies]
stroop-assembly-text.workspace = true
stroop-vm.workspace = true
stroop-vm-bytecode.workspace = true
