[package]
name = "stroop-vm"
description = "Virtual machine implementation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stroop-bytecode = { path = "../stroop-bytecode" }

[dev-dependencies]
stroop-text-assembly = { path = "../stroop-text-assembly" }
codspeed-criterion-compat = "2"

[[bench]]
name = "vm_bench"
harness = false
