[package]
name = "stroop-vm"
description = "Virtual machine implementation"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stroop-vm-bytecode = { path = "../stroop-vm-bytecode" }

[dev-dependencies]
stroop-assembly-text = { path = "../stroop-assembly-text" }
codspeed-criterion-compat = "4"

[[bench]]
name = "vm_bench"
harness = false
