[package]
name = "stroop-assembly-text"
description = "SAT (Stroop Assembly Text) parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
stroop-assembly = { path = "../stroop-assembly" }
stroop-vm-bytecode = { path = "../stroop-vm-bytecode" }
indexmap = "2"

[dev-dependencies]
stroop-vm = { path = "../stroop-vm" }
insta = "1"
